- TOÁN ỨNG DỤNG THỐNG KÊ
- Lớp: 22_3
- Họ và tên: Nguyễn Minh Thiện
- MSSV: 22120344
- Lab 02: Đồ án Gauss – Jordan    

### Giải thuật tìm ma trận nghịch đảo A<sup>-1</sup>
- Bằng phép khử Gauss-Jordan sẽ sử dụng các phép biến đổi ma trận để chuyển ma trận A thành ma trận đơn vị I. Sau đó, áp dụng cùng các biến đổi đó vào ma trận đơn vị I, ta thu được ma trận nghịch đảo A<sup>-1</sup>
- Giải thuật được thực hiện như sau:
    + Bước 1: Tạo ma trận bổ sung A' bằng cách ghép ma trận đơn vị I vào bên phải của ma trận A.
    + Bước 2: Áp dụng phép khử Gauss - Jordan vào ma trận bổ sung A' để chuyển ma trận A thành ma trận bậc thang. Lưu ý rằng phép khử Gauss-Jordan được áp dụng đồng thời vào cả ma trận A và I.
    + Bước 3: Áp dụng phép biến đổi đến ma trận bậc thang A' để chuyển ma trận A thành ma trận đơn vị I.
    + Bước 4: Ma trận đơn vị I' mới thu được sau các phép biến đổi trong bước 2 là ma trận nghịch đảo của ma trận A. Tức là I' chính là ma trận A<sup>-1</sup>


In [7]:
def float_to_fraction(x):
    if x % 1 == 0:
        return str(int(x))
    saiSo = 1.0E-6
    num, denom = 1, 1
    decimal, sign = abs(x), -1 if x < 0 else 1
    while abs(decimal - num/denom) > saiSo:
        if decimal < num/denom:
            denom += 1
        else:
            num += 1
    return f"{sign * num}/{denom}"
    

def print_matrix(A):
    if A is None:
        print('\n')
    else:
        for row in A:
            print([float_to_fraction(elem) for elem in row])
        print('\n')

def create_identity_matrix(n):
    A = []
    for i in range(0, n):
        temp = []
        for j in range(0, n):
            if i == j:
                temp.append(1)
            else:
                temp.append(0)            
        A.append(temp)
    return A

def inverse(A):
    # Kiểm tra nếu ma trận A input không hợp lệ
    for i in range(len(A)):
        if len(A) != len(A[i]):
            print("Ma trận input không vuông, không thể tìm ma trận nghịch đảo!")
            return None
    
    # Tạo ma trận đơn vị In
    B = create_identity_matrix(len(A))
        
    flag = True
    j = 0
    
    # Duyệt qua từng cột của ma trận A
    for i in range(len(A[0])):
        k = j
        flag = False
        
        # Duyệt qua từng dòng của cột đó để kiểm tra cột có giá trị khác 0 hay không
        for l in range(j, len(A)):
            if A[l][i] != 0:
                flag = True
                
        if flag:
            if A[k][i] == 0:
                for z in range(k + 1, len(A)):
                    if A[z][i] != 0:
                        A[k], A[z] = A[z], A[k]
                        B[k], B[z] = B[z], B[k]
                        break
            
            d = (1 / A[k][i])
            for m in range(len(A[0])):
                A[k][m] *= d
                B[k][m] *= d
            
            for k1 in range(len(A)):
                if k1 == i:
                    continue
                d = -A[k1][i] / A[k][i]
                for m in range(len(A[0])):
                    A[k1][m] += d * A[k][m]
                    B[k1][m] += d * B[k][m]
            j += 1
        else:
            print("Ma trận không khả nghịch")
            return None
    return B

# Trường hợp khả nghịch
A = [[0, 1, 2], [1, 2, 1], [1, -1, 3]] 
print("Ma trận A: ")
print_matrix(A)
print("Ma trận nghịch đảo của A: ")
A_inv = inverse(A)
print_matrix(A_inv)

# Trường hợp không khả nghịch
B = [[1, 3, -4], [1, 5, -1], [3, 13, -6]] 
print("Ma trận B: ")
print_matrix(B)
print("Ma trận nghịch đảo của B: ")
B_inv = inverse(B)
print_matrix(B_inv)

# Trường hợp không khả nghịch
C = [[1, 3, -4], [1, 5, -1], [3, 13, -6], [1, 5, 9]] 
print("Ma trận C: ")
print_matrix(C)
print("Ma trận nghịch đảo của C: ")
C_inv = inverse(C)
print_matrix(C_inv)


Ma trận A: 
['0', '1', '2']
['1', '2', '1']
['1', '-1', '3']


Ma trận nghịch đảo của A: 
['-7/8', '5/8', '3/8']
['1/4', '1/4', '-1/4']
['3/8', '-1/8', '1/8']


Ma trận B: 
['1', '3', '-4']
['1', '5', '-1']
['3', '13', '-6']


Ma trận nghịch đảo của B: 
Ma trận không khả nghịch


Ma trận C: 
['1', '3', '-4']
['1', '5', '-1']
['3', '13', '-6']
['1', '5', '9']


Ma trận nghịch đảo của C: 
Ma trận input không vuông, không thể tìm ma trận nghịch đảo!




In [1]:
## Mở rộng: Tìm hiểu hàm/ phương thức tương ứng của các thư viện và thực hiện nó, so sánh kết quả
import numpy as np
def float_to_fraction(x, max_denom=10000, max_iterations=10000):
    if x % 1 == 0:
        return str(int(x))
    saiSo = 1.0E-6
    num, denom = 1, 1
    decimal, sign = abs(x), -1 if x < 0 else 1
    best_num, best_denom, best_diff = num, denom, abs(decimal - num/denom)
    iterations = 0
    while denom <= max_denom and iterations < max_iterations:
        if abs(decimal - num/denom) < best_diff:
            best_diff = abs(decimal - num/denom)
            best_num, best_denom = num, denom
        if decimal < num/denom:
            denom += 1
        else:
            num += 1
        iterations += 1
    return f"{sign * best_num}/{best_denom}"
    
#Trường hợp khả nghịch
A = np.array([[0, 1, 2],
              [1, 2, 1],
              [1, -1, 3]])


#Trường hợp không khả nghịch
B = np.array([[1, 3, -4],
              [1, 5, -1],
              [3, 13, -6]])

#Trường hợp không khả nghịch
C = np.array([[1, 3, -4],
              [1, 5, -1],
              [3, 13, -6],
              [1, 5, 9]])
def compute_matrix_inverse(matrix):
    try:
        inverse_matrix = np.linalg.inv(matrix)
        print("Ma tran nghich dao cua ma tran:")
        for row in inverse_matrix:
            print([float_to_fraction(x) for x in row])
    except np.linalg.LinAlgError:
        print("Ma tran khong kha nghich (khong co ma tran nghich dao).")
print("Ma tran A:")
print(A)
compute_matrix_inverse(A)

print("\nMa tran B:")
print(B)
compute_matrix_inverse(B)

print("\nMa tran C:")
print(C)
compute_matrix_inverse(C)


Ma tran A:
[[ 0  1  2]
 [ 1  2  1]
 [ 1 -1  3]]
Ma tran nghich dao cua ma tran:
['-7/8', '5/8', '3/8']
['1/4', '1/4', '-1/4']
['3/8', '-1/8', '1/8']

Ma tran B:
[[ 1  3 -4]
 [ 1  5 -1]
 [ 3 13 -6]]
Ma tran nghich dao cua ma tran:
['-6380099472108205', '-12760198944216408', '6380099472108204']
['10000/1', '10000/1', '-10000/1']
['-10000/1', '-10000/1', '10000/1']

Ma tran C:
[[ 1  3 -4]
 [ 1  5 -1]
 [ 3 13 -6]
 [ 1  5  9]]
Ma tran khong kha nghich (khong co ma tran nghich dao).


Nhận xét:
- Đối với các ma trận khả nghịch, hàm inverse tự định nghĩa và hàm linalg.inv của thư viện numpy cho kết quả giống nhau
- Đối với ma trận không khả nghịch:
    + Hàm inverse tự định nghĩa sẽ thông báo ma trận không khả nghịch
    + Hàm linalg.inv của thư viện numpy cho ra một ma trận kết quả với các phần tử đều có giá trị vô cùng lớn/vô cùng bé
- Đối với ma trận không vuông:
    + Hàm inverse tự định nghĩa sẽ thông báo ma trận không vuông, không thể tìm ma trận nghịch đảo
    + Hàm linalg.inv của thư viện numpy sẽ thông báo lỗi chương trình

### Mô tả các hàm và ý tưởng thực hiện

1. Hàm print_matrix: dùng để in ra màn hình ma trận được truyền vào hàm
2. Hàm create_identity_matrix: dùng để tạo ra ma trận đơn vị cấp n
- Dùng hai vòng for lồng nhau để lần lượt thêm các giá trị 0 vào ma trận, trừ các phần tử trên đường chéo chính thì giá trị sẽ là 1
3. Hàm inverse: dùng để tìm ma trận nghịch đảo của một ma trận vuông cấp n
- B1: Đầu tiên, kiểm tra ma trận truyền vào có vuông hay không, nếu không vuông thì ngưng hàm
- B2: Nếu ma trận input là ma trận vuông cấp n, tiến hành khởi tạo một ma trận đơn vị B cấp n bằng hàm create_identity_matrix
- B3: Duyệt qua từng cột của ma trận input, nếu cột đang xét có phần tử nằm từ đường chéo chính trở xuống đều bằng 0 thì ngưng hàm, thông báo ma trận không khả nghịch, ngược lại thì thực hiện các bước sau:
    + Kiểm tra nếu phần tử nằm trên đường chéo chính bằng không thì hoán vị dòng chứa phần tử này với dòng có phần tử ở cột tương ứng khác 0 gần nhất với dòng đang xét. Việc này được thực hiện cùng lúc ở ma trận input và ma trận đơn vị B đã tạo ra trước đó.
    + Nhân dòng đang xét của ma trận input và dòng tương ứng của ma trận đơn vị B với 1/(phần tử ở đường chéo chính của ma trận input).
    + Cộng các dòng còn lại của ma trận input và cả ma trận đơn vị B (trừ dòng chứa phần tử nằm trên đường chéo chính) với một số thích hợp để biến các phần tử ở cột đang xét của ma trận input đều bằng 0.
    + Lặp lại B3
- B4: Ma trận đơn vị B được tạo ra ở B2 sau khi thực hiện cả 3 bước trên sẽ là ma trận nghịch đảo của ma trận input, hàm sẽ trả về ma trận B
- ** Lưu ý: Hàm float_to_fraction(x) chỉ để đổi về dạng phân số để có thế dễ kiểm tra